// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_rtJIQfgyBgpwtQ4TzGoH33_WXr20NI',
    appId: '1:245008050907:web:02b870dfc5c76b0f7abafe',
    messagingSenderId: '245008050907',
    projectId: 'pixie-38007',
    authDomain: 'pixie-38007.firebaseapp.com',
    storageBucket: 'pixie-38007.appspot.com',
    measurementId: 'G-8PQ7ZYLVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzN_pzKQ1mvvwMUDWOsYnV3EII73ONtLA',
    appId: '1:245008050907:android:7c255203bce38cfe7abafe',
    messagingSenderId: '245008050907',
    projectId: 'pixie-38007',
    storageBucket: 'pixie-38007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwj5rWZ6TKis8cGmSiENdKpjhImIohek',
    appId: '1:245008050907:ios:1d635e7b0456c74f7abafe',
    messagingSenderId: '245008050907',
    projectId: 'pixie-38007',
    storageBucket: 'pixie-38007.appspot.com',
    iosBundleId: 'com.example.pixieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwj5rWZ6TKis8cGmSiENdKpjhImIohek',
    appId: '1:245008050907:ios:1d635e7b0456c74f7abafe',
    messagingSenderId: '245008050907',
    projectId: 'pixie-38007',
    storageBucket: 'pixie-38007.appspot.com',
    iosBundleId: 'com.example.pixieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo_rtJIQfgyBgpwtQ4TzGoH33_WXr20NI',
    appId: '1:245008050907:web:e6f075bbc7300a677abafe',
    messagingSenderId: '245008050907',
    projectId: 'pixie-38007',
    authDomain: 'pixie-38007.firebaseapp.com',
    storageBucket: 'pixie-38007.appspot.com',
    measurementId: 'G-NSVSPMJWE1',
  );
}
